[Function][Admin] Create Management Words Function
kaz-m-93/e_learning_kazu pull request #22
Opened 2020-11-18 08:45 UTC by kaz-m-93

i created word management function(edit, destroy)
asana:
https://app.asana.com/0/1199094899705013/1199094899705091

2020-11-18 08:59 UTC, CharlotteDS requested changes
Please update your `radio_button` into a `check_box` so that we can have a cleaner and simpler implementation to get `true` or `false` value for `is_correct`.

2020-11-18 09:19 UTC, kaz-m-93 commented
i changed radio button to check box

2020-11-18 09:25 UTC, CharlotteDS reviewed
I want you to add a custom validation in the `word.rb` to check that only one choice is checked.

2020-11-18 09:25 UTC, CharlotteDS commented on app/views/admin/words/_form.html.erb
> +                    <div class="choice-radio"><%= s.check_box :is_correct, value: true , checked: s.object.is_correct ? true : false %></div>
No need to add `value: true , checked: s.object.is_correct ? true : false`.
The value will automatically be true or false, depending if it is checked.
In edit page, the check boxes will automatically get their values from the word's choices.

2020-11-19 06:16 UTC, CharlotteDS approved these changes

2020-11-19 06:18 UTC, merged